### ISSUE TITLE
Paper or figures

### ISSUE THREAD

**Issue by vandana-rajan** [asnelt/mmae#4]
Hi,

Is this mmae with Bregman divergence explained in any research paper? Also, it would be great if you can add a diagram of the mmae architecture.

Thanks,
VR

**Comment by asnelt** [comment]
There is no research paper specifically for mmae. Nevertheless, the approach closely follows the NIPS paper ["A generalization of principal components analysis to the exponential family"](https://papers.nips.cc/paper/2078-a-generalization-of-principal-components-analysis-to-the-exponential-family.pdf) but using deep autoencoders instead of principal component analysis.
